version: '3'
services:
  db:
    image: mysql:8.2.0
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: vollmed
      MYSQL_PASSWORD: vollmed
    volumes:
      - ./data:/var/lib/mysql
